var words = [
  /*   { question: "knowledgeable", answer: "아는것이 많은" },
    { question: "Parking", answer: "주차(공간)" },
    { question: "Openness", answer: "솔직함" },
    { question: "Employee", answer: "직원" },
    { question: "Exercise", answer: "운동" },
    { question: "Weekend", answer: "주말" },
    { question: "All the time", answer: "항상" },
    { question: "East", answer: "동쪽" },
    { question: "Cousin", answer: "사촌" },
    { question: "Dirt", answer: "먼지, 때" },
    { question: "Treatment", answer: "치료(법)" },
    { question: "Receipt", answer: "영수증" },
    { question: "Mistakenly", answer: "실수로" },
    { question: "Mistaken", answer: "잘못된" },
    { question: "Tell", answer: "알다, 말하다" },
    { question: "Differ", answer: "다르다" },
    { question: "Building", answer: "건물" },
    { question: "Largely", answer: "주로" },
    { question: "Arrive", answer: "도착하다" },
    { question: "Arrival", answer: "도착" },
    { question: "Possibly", answer: "아마" },
    { question: "Readily", answer: "기꺼이" },
    { question: "Simplify", answer: "간소화하다" },
    { question: "Simply", answer: "간단히" },
    { question: "Popularize", answer: "대중화하다" },
    { question: "Popularly", answer: "일반적으로, 대중적으로" },
    { question: "Playground", answer: "운동장" },
    { question: "Grow", answer: "기르다" },
    { question: "Condition", answer: "상태, 조건" },
    { question: "Fruit", answer: "과일" },
    { question: "Liar", answer: "거짓말쟁이" },
    { question: "Little sister", answer: "여동생" },
    { question: "Weak", answer: "약한" },
    { question: "Manage", answer: "경영하다" },
    { question: "Management", answer: "경영진, 경영" },
    { question: "Hire", answer: "고용하다" },
    { question: "Consultant", answer: "자문 위원" },
    { question: "Staff", answer: "직원" },
    { question: "Discuss", answer: "논의하다" },
    { question: "Perform", answer: "공연하다" },
    { question: "Receive", answer: "받다" },
    { question: "Review", answer: "평, 평론" },
    { question: "Attend", answer: "참석하다" },
    { question: "Attentive", answer: "주의를 기울이는" },
    { question: "Baggage", answer: "수하물" },
    { question: "Equipment", answer: "장비" },
    { question: "Order", answer: "주문, 주문하다" },
    { question: "Lugage", answer: "수하물" },
    { question: "Priced", answer: "값이 붙은" },
    { question: "Priceless", answer: "값을 매길 수 없는" },
    { question: "refundable", answer: "환불가능한" },
    { question: "outside", answer: "밖에" },
    { question: "meeting", answer: "회의" }, */
  /*  { question: "yard", answer: "마당" }, */
  /*   { question: "pond", answer: "연못" },
    { question: "park", answer: "공원" },
    { question: "restroom", answer: "화장실" },
    { question: "parking lot", answer: "주차장" },
    { question: "air conditioner", answer: "에어컨" },
    { question: "reception desk", answer: "접수처" },
    { question: "airport", answer: "공항" },
    { question: "cage", answer: "새장, 우리" },
    { question: "trash bin", answer: "쓰레기통" },
    { question: "hole", answer: "구멍" },
    { question: "sock", answer: "양말" },
    { question: "drawer", answer: "서랍" },
    { question: "eraser", answer: "지우개" },
    { question: "purse", answer: "지갑" },
    { question: "get", answer: "사다, 얻다" },
    { question: "homework", answer: "숙제, 과제" },
    { question: "interesting", answer: "흥미로운" },
    { question: "move", answer: "옮기다, 이사하다" }, */
  //{ question: "coworker", answer: "동료" },
  /*   { question: "doll", answer: "인형" },
    { question: "fridge", answer: "냉장고" }, */
  /* { question: "discussion", answer: "논의" },
  { question: "classmate", answer: "반 친구" },
  { question: "active", answer: "활동적인" },
  { question: "reading", answer: "독서" },
  { question: "wear", answer: "착용하다" },
  { question: "neighbor", answer: "이웃" },
  { question: "prepare", answer: "준비하다" },
  { question: "doubled", answer: "두 배가 되다" },
  { question: "careful", answer: "세심한" },
  { question: "museum", answer: "미술관" },
  { question: "impressive", answer: "인상 깊은" },
  { question: "excellent", answer: "뛰어난" },
  { question: "excel", answer: "뛰어나다" },
  { question: "wonderfulness", answer: "놀라움" },
  { question: "wonder", answer: "궁금해하다" },
  { question: "wonderful", answer: "멋진" },
  { question: "wonderfully", answer: "놀랍도록" },
  { question: "afford", answer: "살 수 있다." },
  { question: "affordable", answer: "적당한, 알맞은" },
  { question: "left", answer: "남아있는" },
  { question: "country", answer: "나라" },
  { question: "take a rest", answer: "쉬다" },
  { question: "healthy", answer: "건강한" },
  { question: "experienced", answer: "경험이 있는" },
  { question: "necessary", answer: "필요한" },
  { question: "just around the corner", answer: "모퉁이를 돌면 바로 있는, 곧 오는" },
  { question: "leave", answer: "떠나다, 남기다" },
  { question: "wear (상태)", answer: "입고있다 (입고있는 상태)" },
  { question: "put on", answer: "입다(입는동작)" },
  { question: "meet", answer: "만나다, 충족시키다." },
  { question: "expend", answer: "(시간등을) 쓰다" },
  { question: "expansive", answer: "포괄적인" },
  { question: "expand", answer: "확장하다" },
  { question: "skillful", answer: "능숙한" },
  { question: "accomplished", answer: "숙달된" },
  { question: "capable", answer: "유능한" },
  { question: "borrow(돈을 지불 or 돈을 지불x)", answer: "빌리다(돈을 지불x)" },
  { question: "rent(돈을 지불 or 돈을 지불x)", answer: "빌리다(돈을 지불)" },
  { question: "sale", answer: "판매(량), 세일, 할인행사" }, */
  /*   { question: "discount", answer: "할인" },
    { question: "convenient", answer: "편리한" }, */
  /*   { question: "missing", answer: "빠진, 없어진" },
    { question: "return", answer: "반품하다" },
    { question: "location", answer: "지점" },
    { question: "position", answer: "일자리, 직무" },
    { question: "offer", answer: "제공하다" },
    { question: "sales", answer: "판매직" }, */
  //
  /*     { question: "reader", answer: "독자" },
      { question: "cost", answer: "비용이 들다" },
      { question: "often", answer: "종종" },
      { question: "invition", answer: "초대장" },
      { question: "indoors", answer: "실내에서" },
      { question: "speaker", answer: "연설자" },
      { question: "summary", answer: "요약" },
      { question: "tax", answer: "세금" },
      { question: "activity", answer: "활동" },
      { question: "prepare", answer: "준비하다" },
      { question: "of", answer: "~의, ~중에서" },
      { question: "rate", answer: "평가하다" },
      { question: "poor", answer: "미흡한" },
      { question: "fair", answer: "보통" },
      { question: "dish", answer: "요리, 접시" },
      { question: "least", answer: "가장 적게" },
      { question: "cleaniness", answer: "청결" }, */
  /*   { question: "cozy", answer: "아늑한" },
    { question: "loudly", answer: "시끄럽게" },
    { question: "careful", answer: "주의 깊은" },
    { question: "closely", answer: "주의 깊게" },
    { question: "lately", answer: "최근에" },
    { question: "hardly", answer: "거의 ~않다" },
    { question: "mostly", answer: "주로" },
    { question: "highly", answer: "매우" },
    { question: "nearly", answer: "거의" }, */
  /*   { question: "because of", answer: "~때문에" },
    { question: "laziness", answer: "게으름" },
    { question: "closure", answer: "폐쇄" },
    { question: "even", answer: "심지어" },
    { question: "frequently", answer: "빈번하게" },
    { question: "rarely", answer: "거의 ~않다" },
    { question: "seldom", answer: "거의 ~않다" },
    { question: "scarcely", answer: "거의 ~않다" },
    { question: "barely", answer: "거의 ~않다" },
    { question: "drop", answer: "하락하다, 떨어지다" },
    { question: "fluent", answer: "유창한" },
    { question: "confidence ", answer: "확신, 자신감" },
    { question: "own", answer: "소유하다" },
    { question: "department store", answer: "백화점" },
    { question: "applicant", answer: "지원자" },
    { question: "resume, résumé", answer: "다시 시작하다, 이력서" }, */
  /* { question: "turn off", answer: "~을 끄다" },
  { question: "spill", answer: "쏟다" },
  { question: "lounge", answer: "휴게실" },
  { question: "due to", answer: "~때문에" },
  { question: "owing to", answer: "~때문에" },
  { question: "despite", answer: "~에도 불구하고" },
  { question: "in spite of", answer: "~에도 불구하고" },
  { question: "for", answer: "~을 위하여, 왜냐하면" },
  { question: "regarding", answer: "~에 대해" },
  { question: "concerning", answer: "~에 대해" },
  { question: "with", answer: "~와 함깨, ~을 가지고" },
  { question: "by", answer: "~에 의해, ~으로" },
  { question: "chopstick", answer: "젓가락" },
  { question: "hold", answer: "열다, 쥐다" },
  { question: "textbook", answer: "교과서" },
  { question: "last", answer: "지속되다, 마지막" },
  { question: "beside", answer: "~옆에" },
  { question: "aisle", answer: "통로" },
  { question: "plice officer", answer: "경찰관" },
  { question: "attentive", answer: "세심한" },
  { question: "suitcase", answer: "여행 가방" },
  { question: "sure", answer: "확신하다" },
  { question: "raise", answer: "오르다, 모으다, 기르다" },
  { question: "accounting", answer: "회계" },
  { question: "nearby", answer: "인근에" },
  { question: "intelligent", answer: "똑똑한" },
  { question: "exam", answer: "시험" },
  { question: "necklace", answer: "목걸이" },
  { question: "diligent", answer: "부지런한" },
  { question: "invest", answer: "투자하다" },
  { question: "funds", answer: "자금" },
  { question: "decade", answer: "10년" },
  { question: "planet", answer: "행성" },
  { question: "holiday", answer: "휴일" },
  { question: "appoach", answer: "접근하다" },
  { question: "account for", answer: "~에 대해 설명하다" },
  { question: "figure", answer: "수치, 두드러지다" },
  { question: "break out", answer: "발생하다" },
  { question: "break down", answer: "고장나다" },
  { question: "break into", answer: "~에 침입하다" },
  { question: "hold on", answer: "기다리다" },
  { question: "on hold", answer: "연기하다, 잠시 기다리게 하다" },
  { question: "World Warr II", answer: "2차세계대전" },
  { question: "poor", answer: "가난한" },
  { question: "professor", answer: "교수" },
  { question: "chairman", answer: "의장" },
  { question: "deal", answer: "처리하다" }, */
  // { question: "", answer: "" },


  // -- 토익 영단어 end --
  /*   { question: "acknowledgment", answer: "인정, 사례" },
    { question: "reviewer", answer: "평론가" },
    { question: "ideal", answer: "이상" },
    { question: "etiquette", answer: "예절" },
    { question: "perception", answer: "지각, 인지" },
    { question: "endanger", answer: "위험에 빠트리다" },
    { question: "vocabulary", answer: "어휘" },
    { question: "engage", answer: "계약하다" },
    { question: "integrate", answer: "통합하다" },
    { question: "touchstone", answer: "표준" },
    { question: "for", answer: "~을 위하여, 왜냐하면" },
    { question: "contemporary", answer: "같은 시대의" },
    { question: "authentic", answer: "진짜의" },
    { question: "topic", answer: "주제" },
    { question: "offer", answer: "제공하다" },
    { question: "assessment", answer: "평가" },
    { question: "outcome", answer: "결과" },
    { question: "scaffold", answer: "발판" },
    { question: "unit", answer: "단일체, 구성" },
    { question: "inference", answer: "추리" },
    { question: "margin", answer: "여백, 여유" },
    { question: "predict", answer: "예측하다" },
    { question: "possessive", answer: "소유의" },
    { question: "adjective", answer: "형용사" },
    { question: "paragraph", answer: "절" },
    { question: "descriptive", answer: "기술적인, 설명적인" },
    { question: "offbeat", answer: "색다른, 별난" }, */
  // --[2024-3-4]
  /*   { question: "peer", answer: "동등한" },
    { question: "pronoun", answer: "대명사" },
    { question: "proper", answer: "적당한" },
    { question: "deity", answer: "신" },
    { question: "conjunction", answer: "접속사" },
    { question: "dormitory", answer: "기숙사" },
    { question: "decide", answer: "결정을 내리다" },
    { question: "karaoke", answer: "노래방" },
    
    { question: "outgoing", answer: "외향적인" },
    { question: "phrases", answer: "구" },
    { question: "preposition", answer: "전치사" },
    { question: "capital", answer: "대문자" },
    { question: "abbriviation", answer: "생략" },
    { question: "acronym", answer: "머리글자" },
    { question: "title", answer: "직함, 제목" },
    { question: "monument", answer: "기념비" }, */
  // 2024-3-6
  /*   { question: "insurance", answer: "보험" },
    { question: "hours", answer: "몇시간" },
    { question: "spend", answer: "소비하다" },
    { question: "resume", answer: "이력서" },
    { question: "Parachute", answer: "낙하산" },
    { question: "expert", answer: "전문가" },
    { question: "exercise", answer: "연습, 운동" },
    { question: "individual", answer: "개인" },
    { question: "infer", answer: "추론" },
    { question: "anyone", answer: "누군가" },
    { question: "sentence", answer: "문장" },
    { question: "bought", answer: "구매했다" },
    { question: "taught", answer: "가르쳤다" },
    { question: "melt", answer: "녹다" },
    { question: "necessary", answer: "필요한" },
    { question: "predict", answer: "예측하다" },
    { question: "erupt", answer: "폭발하다" },
    { question: "antarctica", answer: "남극 대륙" },
    { question: "salary", answer: "급료" },
    { question: "liquid", answer: "액채" },
    { question: "individual", answer: "개인의, 개별의" }, */

  // [2024-03-09]
  /*   { question: "lobby", answer: "로비" },
    { question: "for free", answer: "무료로" },
    { question: "evaluate", answer: "평가하다" },
    { question: "particle", answer: "입자" },
    { question: "cause", answer: "야기하다" },
    { question: "hire", answer: "고용하다, 신입사원" },
    { question: "already", answer: "이미" },
    { question: "deceive", answer: "속이다" },
    { question: "depart", answer: "출발하다" },
    { question: "temporary", answer: "일시적인" },
    { question: "complained", answer: "불평하다" },
    { question: "sure", answer: "확신하다" },
    { question: "call", answer: "부르다, 전화" },
    { question: "exam", answer: "시험" },
    { question: "instead", answer: "대신에" }, */

  // [2024-03-10]
  /*   { question: "sell", answer: "팔리다" },
    { question: "equipment", answer: "장비" },
    { question: "children", answer: "아이들" },
    { question: "onion", answer: "양파" },
    { question: "attract", answer: "끌다" },
    { question: "due", answer: "~때문에" },
    { question: "patient", answer: "환자" },
    { question: "invite", answer: "초대하다" },
    { question: "sold out", answer: "매진된" },
    { question: "be left", answer: "남다" },
    { question: "apply to", answer: "~에 적용되다" },
    { question: "apply for", answer: "~을 신청하다, 지원하다" },
    { question: "point of view", answer: "견해" },
    { question: "conference", answer: "강연" },
    { question: "malfunction", answer: "오작동" },
    { question: "these days", answer: "요즘에" },
    { question: "nowadays", answer: "요즘에" },
    { question: "advertise", answer: "광고" },
    { question: "strictly", answer: "엄격히" },
    { question: "about(부사)", answer: "약" },
    { question: "around", answer: "주위에, 약" },
    { question: "approximately", answer: "약" }, */

  // 2024-03-13
  /*   { question: "concert", answer: "콘서트" },
    { question: "tomorrow", answer: "내일" },
    { question: "reserve", answer: "예매하다" },
    { question: "retire", answer: "은퇴하다" },
    { question: "lunch box", answer: "도시락" },
    { question: "brought", answer: "가져왔다" }, */
  /*   { question: "so far", answer: "지금" },
    { question: "paint", answer: "페인트칠을 하다" }, */
  /*   { question: "fall asleep", answer: "잠들다" },
    { question: "work on", answer: "~을 작업하다" },
    { question: "come to an agreement", answer: "합의에 도닳하다" },
    { question: "job seeker", answer: "구직자" },
    { question: "employment rate", answer: "취업률" },
    { question: "unemployment rate", answer: "실업률" }, */
  /*   { question: "since + 명사/문장", answer: "~이래로" },
    { question: "since + 문장(s+v)", answer: "~때문에" },
    { question: "and yet", answer: "그런데도" }, */
  /*   { question: "contributed to", answer: "~에 기여하다" },
    { question: "ring", answer: "(초인종을) 누르다" },
    { question: "come to", answer: "오다" },
    { question: "agreement", answer: "합의" }, */

  // 2024-03-14
  /*   { question: "dye", answer: "물감" },
    { question: "authority", answer: "당국, 건위" },
    { question: "guinness", answer: "기네스" },
    { question: "spectator", answer: "관중" },
    { question: "missionary", answer: "선교사, 광신적인" },
    { question: "scholar", answer: "학자" },
    { question: "semester", answer: "한 학기" },
    { question: "cliff", answer: "절벽" },
    { question: "motorcycle", answer: "오토바이" },
    { question: "exchange", answer: "교환하다" },
    { question: "survey", answer: "조사, 검사" },
    { question: "involve", answer: "포함하다" },
    { question: "shock", answer: "충격을 주다" },
    { question: "frighten", answer: "섬뜩하게 하다" },
    { question: "plased", answer: "기분 좋은" },
    { question: "highway", answer: "고속도로" },
    { question: "equip", answer: "갖추어 지다" },
    { question: "furniture", answer: "가구" },
    { question: "expose", answer: "드러나다" },
    { question: "sensitive", answer: "예민한" },
    { question: "row", answer: "열, 줄" },
    { question: "post office", answer: "우체국" },
    { question: "mail", answer: "우편물, 보내다" },
    { question: "critic", answer: "비평가" },
    { question: "book an appointment", answer: "예약하다" },
    { question: "speech", answer: "발표" },
    { question: "communicate", answer: "의사소통하다" },
    { question: "confident", answer: "자신있다" }, */

  // 2024-03-16
  /*   { question: "put on", answer: "~을 입다." },
    { question: "take off", answer: "~을 벗다" },
    { question: "tie", answer: "묶다" },
    { question: "bend", answer: "(무릎을)꿇다, (고개를)숙이다" },
    { question: "lean", answer: "기대다" },
    { question: "reach for", answer: "손을 뻗다" },
    { question: "hand", answer: "손, 건내다" },
    { question: "get on", answer: "~타다" },
    { question: "boarding", answer: "탑승하다" },
    { question: "enter", answer: "들어가다" }, */
  // 2024-03-17
  /*   { question: "be good at", answer: "~를 잘한다" },
    { question: "convenient", answer: "편리한" },
    { question: "promote", answer: "홍보하다" },
    { question: "attempt", answer: "시도하다" },
    { question: "intend", answer: "의도하다" },
    { question: "walkway", answer: "보도" },
    { question: "covered", answer: "덮여있다" },
    { question: "vehicle", answer: "차량" },
    { question: "set up", answer: "세워져 있다" },
    { question: "dock", answer: "부두" },
    { question: "floating", answer: "떠 있다" },
    { question: "path", answer: "길" },
    { question: "plant", answer: "식물, 심다" },
    { question: "lined up", answer: "줄 세워져 있다" },
    { question: "There is/are", answer: "~이 있다" },
    { question: "beside", answer: "옆에" },
    { question: "set", answer: "놓여 있다" },
    { question: "placed", answer: "놓여 있다" },
    { question: "arranged", answer: "배치되어 있다" },
    { question: "positioned", answer: "배치되어 있다" },
    { question: "on display", answer: "전시되어 있다" },
    { question: "piled", answer: "쌓여 있다" }, */
  /*   { question: "stacked", answer: "쌓여 있다" },
    { question: "hung/hanging", answer: "걸려 있다" },
    { question: "posted", answer: "게시되어 있다" },
    { question: "poured", answer: "따라져 있다" },
    { question: "cabinet", answer: "수납장" },
    { question: "plate", answer: "접시" },
    { question: "kneel", answer: "무릎을 꿇다" },
    { question: "pot", answer: "항아리, 단지" }, */

  // 2024-03-18
  { question: "homonyms", answer: "동음이의어" },
  { question: "synonyms", answer: "동의어" },
  { question: "antonyms", answer: "반의어" },
  { question: "homographs", answer: "철자" },
  /* { question: "bare", answer: "벗다" }, */
  { question: "pronunciation", answer: "발음" },
  { question: "pronounce", answer: "발음하다" },
  /* { question: "usage", answer: "사용" },
  { question: "period", answer: "기간" },
  { question: "transportation", answer: "교통" },
  { question: "crowed", answer: "소리질렀다" },
  { question: "urban", answer: "도시의" },
  { question: "pollute", answer: "오염시키다" },
  { question: "rural", answer: "시골의" },
  { question: "rubuish bin", answer: "쓰레기통" },
  { question: "fragrance", answer: "향기로운" },
  { question: "aroma", answer: "향기가 나다" },
  { question: "scent", answer: "향기를 맡다" },
  { question: "heir", answer: "상속인" },
  { question: "flight", answer: "항공편" },
  { question: "horizontal", answer: "가로의" },
  { question: "vertical", answer: "세로의" }, */
  /*  { question: "won't(will not)", answer: "~않을 것이다" },
    { question: "fair", answer: "박람회" },
    { question: "fare", answer: "요금" },
    { question: "brake", answer: "브레이크" },
    { question: "here", answer: "여기에" },
    { question: "weight", answer: "무계" },
    { question: "book", answer: "책, 예매하다" },
    { question: "within", answer: "~이내에, ~의 속에" },
    { question: "borrow", answer: "빌리다" },
    { question: "pardon me?", answer: "잘못들었습니다?" },
    // 2024-03-20
    { question: "return", answer: "반품, 되돌아가다" },
    { question: "brochure", answer: "책자" },
    { question: "saw", answer: "봤다, 톱" },
    { question: "entertain", answer: "즐겁게 하다" },
    { question: "save", answer: "구하다, 남겨두다, 지키다" },
    { question: "tire", answer: "지치게 하다" },
    { question: "technician", answer: "기술자" },
    { question: "disappoint", answer: "실망시키다" },
    { question: "bore", answer: "지루하게 하다" },
    { question: "pleasure", answer: "즐거움" },
    */
  { question: "compliment", answer: "칭찬" },
  { question: "instructor", answer: "지도자" },
  { question: "wireless", answer: "무선의" },
  { question: "department", answer: "분야" },
  { question: "tail", answer: "옷 자락" },
  { question: "sleeve", answer: "소매" },

  //2024-03-21
  { question: "finish", answer: "끝내다, 끝 마무리" },
  { question: "renovate", answer: "수리하다" },
  { question: "prefer", answer: "선호하다" },
  { question: "congestion", answer: "혼잡" },
  { question: "(접속사, 전치사)like", answer: "~처럼" },
  { question: "spending", answer: "지출" },
  { question: "considerate", answer: "사려 깊은" },
  { question: "considerable", answer: "상당한" },
  { question: "as usual", answer: "평소처럼" },
  { question: "restructure", answer: "재구성하다" },
  { question: "goverment", answer: "정부" },

  // 2024-03-24
  { question: "clear", answer: "분명한, 맑아지다" },
  { question: "flavor", answer: "맛" },
  { question: "familiar", answer: "잘 알고 있는, 익숙한" },
  { question: "responsible", answer: "책임이 있는" },
  { question: "become", answer: "~이 되다." },
  { question: "study", answer: "공부, 연구" },
  { question: "certain", answer: "특정한, 확신하는" },
  { question: "find out", answer: "~을 알아내다" },
  { question: "graduated from", answer: "~를 졸업하다" },

  // 2024-03-25
  { question: "minute", answer: "작은, 분" },
  { question: "trunk", answer: "코끼리, 가방, 기둥" },
  { question: "british english", answer: "영국식 영어" },
  { question: "quit", answer: "그만두다, 중지하다" },
  { question: "trunk", answer: "줄기, 코끼리, 가방" },
  { question: "instruction", answer: "정보" },
  { question: "direction", answer: "방향, 방침" },
  { question: "first semestor", answer: "1학기" },
  { question: "second semestor", answer: "2학기" },
  { question: "freshmen(man)", answer: "1학년" },
  { question: "sophomore", answer: "2학년" },
  { question: "junior", answer: "3학년" },
  { question: "senior", answer: "4학년" },
  { question: "quiet", answer: "조용한" },
  { question: "miss", answer: "그리워하다, 놓치다" },
  { question: "adverb", answer: "부사" },
  { question: "presentation", answer: "발표" },
  { question: "on sale", answer: "할인 중인" },
  { question: "years old, year old", answer: "~살" },
  { question: "similar", answer: "비슷한" },
  { question: "plenty", answer: "대량" },

  // 2024-03-26
  { question: "possessive", answer: "소유의" },
  { question: "curly", answer: "곱슬곱슬한" },
  { question: "messy", answer: "지저분한" },
  { question: "so far", answer: "지금" },
  { question: "out of", answer: "밖으로" },
  { question: "doubt", answer: "확신하지 못하다" },
  { question: "dependent", answer: "의존하는" },
  { question: "dependable", answer: "믿을수있는" },
  { question: "cheap", answer: "저렴한" },
  { question: "of", answer: "~중에" },
  { question: "living room", answer: "거실" },
  { question: "avoid", answer: "피하다" },
  { question: "repeat", answer: "반복하다" },
  { question: "infer", answer: "추론하다" },
  { question: "fiquarative", answer: "비유적인" },
  { question: "get there", answer: "거기에 가다" },
  { question: "variable", answer: "변수" },
  // 듣기 단어 1
  { question: "ago", answer: "전에" },
  { question: "log on", answer: "로그인 하다" },
  { question: "replace", answer: "교체하다" },
  { question: "review", answer: "검토하다" },
  { question: "cart", answer: "수레" },
  { question: "across", answer: "건너서" },
  { question: "inspect", answer: "점검하다, 조사하다" },
  { question: "place", answer: "놓다" },
  { question: "present", answer: "선물, 발표하다" },
  { question: "fine", answer: "좋은, 벌금" },
  { question: "change", answer: "잔돈, 바꾸다" },
  { question: "ship", answer: "배, 운송하다" },
  { question: "press", answer: "신문, 언론, 누르다" },
  { question: "stop", answer: "정류장, 멈추다" },
  { question: "set", answer: "세트, 놓다" },
  { question: "To ~", answer: "~하기 위해서" },
  { question: "cloudy", answer: "흐린" },
  { question: "certainly", answer: "기꺼이" },
  { question: "secretary", answer: "비서" },

  // 2024-03-28
  { question: "state", answer: "진술하다" },
  { question: "settler", answer: "정착자" },
  { question: "congregate", answer: "모이다" },
  { question: "passerby", answer: "행인" },
  { question: "pedestrian", answer: "보행자" },
  { question: "preserved", answer: "보존된" },
  { question: "wear(명사)", answer: "닮은" },
  { question: "sign", answer: "신호, 서명하다" },
  { question: "package", answer: "소포" },
  { question: "as", answer: "~할 때, ~함에 따라" },
  { question: "as soon as", answer: "~하자마자" },
  { question: "unless", answer: "만약 ~하지 않는다면" },
  { question: "once", answer: "일단 ~하면" },
  { question: "as long as", answer: "~하는 한" },

  // 2024-03-30
  { question: "shelve", answer: "선반" },
  { question: "break", answer: "휴식" },
  { question: "convention", answer: "회의" },

  // 2024-04-01
  { question: "territory", answer: "영토" },
  { question: "stressed", answer: "강세" },
  { question: "province", answer: "지방" },
  { question: "contrcation", answer: "단축" },
  { question: "academic", answer: "대학의, 학구적인" },
  { question: "department", answer: "부문, (백화점등의)매장, 학부, 과" },
  { question: "administration", answer: "행정부" },
  { question: "athletics team", answer: "육상팀" },
  { question: "car park", answer: "주차장" },
  { question: "dorm", answer: "기숙사" },
  { question: "english literature", answer: "영문학" },
  { question: "political", answer: "정치적인" },
  { question: "student union", answer: "학생 조합" },
  { question: "hyphen", answer: "-" },

  //2024-04-02
  { question: "draft", answer: "초안, 도면" },
  { question: "revise", answer: "수정하다" },

  // 2024-04-09
  { question: "nothing", answer: "아무것도 없음" },
  { question: "irregular", answer: "불규칙적인" },

  // 2024-04-19 [듣기]
  { question: "take", answer: "~이 걸리다" },
  { question: "around", answer: "~쯤" },
  { question: "within", answer: "~이내에" },
  { question: "for / during", answer: "~ 동안" },
  { question: "once", answer: "일단 ~하면" },
  { question: "as soon as", answer: "~하자마자" },

  // 2024-04-21 [듣기]
  { question: "work hours", answer: "근무 시간" },
  { question: "business trip", answer: "출장" },
  { question: "position", answer: "직책" },
  { question: "cover", answer: "다루다" },
  { question: "be held", answer: "열리다" },
  { question: "sign up", answer: "등록하다" },
  { question: "sales", answer: "매출, 영업" },
  { question: "survey", answer: "설문조사" },
  { question: "resarch", answer: "연구, 조사" },
  { question: "product", answer: "상품" },
  { question: "give away", answer: "나누어주다" },
  { question: "clinic", answer: "병원" },
  { question: "checkup", answer: "검진" },
  { question: "fill out", answer: "작성하다" },
  { question: "fee", answer: "수수료" },
  { question: "pick up", answer: "~을 찾아오다" },

  // 2024-04-21
  { question: "day", answer: "낮" },
  // { question: "", answer: "" },

  // 토익 2024-04-29
  { question: "sold out", answer: "매진된" },
  { question: "clinic", answer: "병원" },
  { question: "checkup", answer: "검진" },
  { question: "fill out", answer: "기입하다" },
  { question: "replace", answer: "교체하다" },
  { question: "fee", answer: "요금, 수수료" },
  { question: "pick up", answer: "~을 찾아오다" },
  { question: "museum", answer: "박물관" },
  { question: "reservation", answer: "예약하다" },
  { question: "move to", answer: "이사하다" },
  { question: "station", answer: "역" },
  { question: "transfer", answer: "환승하다" },

  // 토익 2024-04-30
  { question: "most likely", answer: "아마" },
  { question: "likely", answer: "~할거같은" },
  { question: "however", answer: "그러나, 아무래 ~해도" },
  { question: "aisle", answer: "통로" },
  { question: "unavailable", answer: "손에 넣을 수 없는" },

  // { question: "", answer: "" },
];
// -------------------------- 단어 end --------------------------


// c start
/*   { question: "strength", answer: "힘" },
  { question: "difine", answer: "정의하다" },
  { question: "constant", answer: "끊임없는" },
  { question: "format", answer: "크기, 구성하다" },
  { question: "sprung", answer: "싹트다" },
  { question: "foremost", answer: "선두의" },
  { question: "prominence", answer: "눈에 띄는" },
  { question: "apparent", answer: "식별할 수 있는" },
  { question: "laboratory", answer: "실험실" },
  { question: "convey", answer: "운반하다" },
  { question: "flavor", answer: "맛" },
  { question: "immerse", answer: "적시다, 빠져들게 하다" },
  { question: "decide", answer: "결정하다" },
  { question: "ancestry", answer: "조상" },
  { question: "diverge", answer: "갈라지다" },
  { question: "portability", answer: "휴대할 수 있음, 이식성" },
  { question: "evolve", answer: "진화하다" },
  { question: "period", answer: "기간" },
  { question: "absence", answer: "부재중의" },
  { question: "aficionados", answer: "마니아" },
  { question: "de", answer: "~에서, ~에 대하여" },
  { question: "facto", answer: "사실상의" },
  { question: "popularity", answer: "인기" },
  { question: "rely", answer: "의지하다" },
  { question: "fuzzy", answer: "모호" },
  { question: "distinction", answer: "변별력" },
  { question: "belong", answer: "속하다" },
  { question: "precise", answer: "정밀한" },
  { question: "dialect", answer: "방언" },
  { question: "arise", answer: "생기다" },
  { question: "threatening", answer: "위협적" },
  { question: "major", answer: "주요한, 전공하다" },
  { question: "appendix", answer: "부가물, 덧붙이다" },
  { question: "auspices", answer: "후원의" },
  { question: "revision", answer: "수정하다" },
  { question: "summarize", answer: "요약하다" },
  { question: "underwent", answer: "undergo 과거" },
  { question: "ambiguous", answer: "모호한" },
  { question: "universal", answer: "보편적인" },
  { question: "derive", answer: "파생되다, 끌어내다" },
  { question: "whether", answer: "~인지 아닌" },
  { question: "abstraction", answer: "추상" },
  { question: "tackle", answer: "부딪치다" },
  { question: "stem", answer: "줄기" },
  { question: "correspond", answer: "일치하다" },
  { question: "underlie", answer: "~의 기초가 되다." },
  { question: "procedure", answer: "절차" },
  { question: "latitude", answer: "위도" },
  { question: "moreover", answer: "게다가" },
  { question: "mandate", answer: "권한" },
  { question: "efficiency", answer: "효율성" },
  { question: "intend", answer: "의도하다" },
  { question: "splinter", answer: "쪼개지다" },
  { question: "incompatible", answer: "양립할 수 없는" },
  { question: "bit", answer: "조금" },
  { question: "restriction", answer: "제한" },
  { question: "impose", answer: "도입하다" },
  { question: "notorious", answer: "유명한" },
  { question: "closeness", answer: "친밀감" },
  { question: "prone", answer: "쉬운" },
  { question: "pitfall", answer: "함점" },
  { question: "unwary", answer: "경솔한" },
  { question: "these", answer: "이것들" },
  { question: "contrast", answer: "대조하다" },
  { question: "indicate", answer: "지시하다" },
  { question: "yield", answer: "양보" },
  { question: "so far", answer: "지금까지" },
  { question: "invoke", answer: "발동하다" },
  { question: "detect", answer: "탐지하다" },
  { question: "highlight", answer: "돋보이게 하다" },
  { question: "variation", answer: "변화" },
  { question: "among", answer: "~의 사이에" },
  { question: "however", answer: "하지만" },
  { question: "brace", answer: "떠받치다" },
  { question: "elsewhere", answer: "다른 곳에" },
  { question: "abbreviation", answer: "생략" },
  { question: "concise", answer: "간결한" },
  { question: "parentheses", answer: "괄호" },
  { question: "perform", answer: "수행하다" },
  { question: "lack", answer: "부족한" },
  { question: "enclose", answer: "둘러싸다" },
  { question: "quotation mark", answer: "더블코트" },
  { question: "shipping", answer: "배송" },
  { question: "initialization", answer: "초기화" },
  { question: "formula", answer: "형식적인 문구" },
  { question: "manufacture", answer: "제조하다" },
  { question: "avoid", answer: "피하다" },
  { question: "operand", answer: "피연산자" ㄷ
// in c end
*/




